s = (insert|create) <';'>?

insert = <k_insert> <k_into> n_table l_column <k_values> l_value
create = <k_create> <k_table> n_table l_d_column

l_column = <l_paren> (n_column | n_column (<comma> n_column)*)+  <r_paren>
l_value = <l_paren> (n_value | n_value (<comma> n_value)*) <r_paren>
l_d_column = <l_paren> (d_column | d_column (<comma> d_column)*)+ <r_paren>

d_column = d_id d_type d_col_constraint
d_id = id
<d_type> = d_number | d_string
d_col_constraint = (k_not_null | k_primary_key | d_default)*
d_default = <'default'> n_value
d_number = 'number' <l_paren> <positive_int> <comma> <positive_int> <r_paren>
d_string = 'varchar2' <l_paren> <positive_int> <r_paren>

k_insert = 'insert'
k_into = 'into'
k_values = 'values'
k_create = 'create'
k_table = 'table'
k_not_null = <#"not\s+null">
k_primary_key = <#"primary\s+key">

<n_column> = id
<n_value> = string | number
n_table = id

<id> = #"[a-zA-Z][_a-zA-Z0-9]*"
space = #"\s"
<comma> = ','
l_paren = '('
r_paren = ')'
<positive_int> = <digit+>
<string> = #"'[a-zA-Z]+'"
<number> = #"([+-])?[0-9]+(\.?[0-9]*)"
<digit> = #"[0-9]"
